services:
  - name: tea-backend
    type: web
    env: python
    plan: free
    region: oregon
    buildCommand: |
      cd tea-backend
      pip install -r requirements.txt
    startCommand: |
      cd tea-backend
      ./start.sh

  - name: tea-frontend
    type: web
    env: static
    plan: free
    region: oregon
    buildCommand: |
      cd tea-frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://tea-backend.onrender.com"
