"""new structure works for sure this time for sure

Revision ID: 006d478bd8f9
Revises: 
Create Date: 2025-05-05 20:29:17.053502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006d478bd8f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('accountid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('passwordhash', sa.Text(), nullable=False),
    sa.Column('createdat', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('accountid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_accounts_accountid'), 'accounts', ['accountid'], unique=False)
    op.create_index(op.f('ix_accounts_createdat'), 'accounts', ['createdat'], unique=False)
    op.create_table('posts',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=240), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('createdat', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lastedited', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['accountid'], ['accounts.accountid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_index(op.f('ix_posts_createdat'), 'posts', ['createdat'], unique=False)
    op.create_index(op.f('ix_posts_postid'), 'posts', ['postid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_postid'), table_name='posts')
    op.drop_index(op.f('ix_posts_createdat'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_accounts_createdat'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_accountid'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
