"""Drop followers and like tables, add likes column to posts

Revision ID: 3ae52a4b64c1
Revises: 
Create Date: 2025-05-05 17:39:57.492087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae52a4b64c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_table('likes')
    op.create_index(op.f('ix_accounts_accountid'), 'accounts', ['accountid'], unique=False)
    op.create_index(op.f('ix_accounts_createdat'), 'accounts', ['createdat'], unique=False)
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_createdat'), 'posts', ['createdat'], unique=False)
    op.create_index(op.f('ix_posts_postid'), 'posts', ['postid'], unique=False)
    op.drop_constraint('posts_parentpostid_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'parentpostid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('parentpostid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_parentpostid_fkey', 'posts', 'posts', ['parentpostid'], ['postid'], ondelete='CASCADE')
    op.drop_index(op.f('ix_posts_postid'), table_name='posts')
    op.drop_index(op.f('ix_posts_createdat'), table_name='posts')
    op.drop_column('posts', 'likes')
    op.drop_index(op.f('ix_accounts_createdat'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_accountid'), table_name='accounts')
    op.create_table('likes',
    sa.Column('accountid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('postid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['accountid'], ['accounts.accountid'], name='likes_accountid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postid'], ['posts.postid'], name='likes_postid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('accountid', 'postid', name='likes_pkey')
    )
    op.create_table('followers',
    sa.Column('followerid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followingid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followerid'], ['accounts.accountid'], name='followers_followerid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['followingid'], ['accounts.accountid'], name='followers_followingid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('followerid', 'followingid', name='followers_pkey')
    )
    # ### end Alembic commands ###
