"""Drop followers and like tables, add likes column to posts

Revision ID: 3ae52a4b64c1
Revises: 
Create Date: 2025-05-05 17:39:57.492087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae52a4b64c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'accounts',
        sa.Column('accountid', sa.Integer, primary_key=True),
        sa.Column('email', sa.String(255), nullable=False, unique=True),
        sa.Column('username', sa.String(50), nullable=False, unique=True),
        sa.Column('passwordhash', sa.Text, nullable=False),
        sa.Column('createdat', sa.TIMESTAMP, server_default=sa.func.now(), index=True),
    )

    op.create_table(
        'posts',
        sa.Column('postid', sa.Integer, primary_key=True),
        sa.Column('accountid', sa.Integer, sa.ForeignKey('accounts.accountid', ondelete='CASCADE'), nullable=False),
        sa.Column('content', sa.String(240), nullable=False),
        sa.Column('likes', sa.Integer, nullable=True),
        sa.Column('createdat', sa.TIMESTAMP, server_default=sa.func.now(), index=True),
        sa.Column('lastedited', sa.TIMESTAMP, nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('parentpostid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_parentpostid_fkey', 'posts', 'posts', ['parentpostid'], ['postid'], ondelete='CASCADE')
    op.drop_index(op.f('ix_posts_postid'), table_name='posts')
    op.drop_index(op.f('ix_posts_createdat'), table_name='posts')
    op.drop_column('posts', 'likes')
    op.drop_index(op.f('ix_accounts_createdat'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_accountid'), table_name='accounts')
    op.create_table('likes',
    sa.Column('accountid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('postid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['accountid'], ['accounts.accountid'], name='likes_accountid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postid'], ['posts.postid'], name='likes_postid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('accountid', 'postid', name='likes_pkey')
    )
    op.create_table('followers',
    sa.Column('followerid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followingid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followerid'], ['accounts.accountid'], name='followers_followerid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['followingid'], ['accounts.accountid'], name='followers_followingid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('followerid', 'followingid', name='followers_pkey')
    )
    # ### end Alembic commands ###
